### ISSUE TITLE
Event query sample in readme doesn't work.

### ISSUE THREAD

**Issue by de0xy** [mfesiem/msiempy#42]
First of all, thank you for your work on this project. There's not a lot of resources out there for this kind of stuff.

I'm running the example event query script on the `README.md` page, but I run into this `msiempy.NitroError: Sorry the filters must be either a tuple(fiels, [values]) or a QueryFilter sub class.` error.

##### Script being used
```
import msiempy.event
import msiempy.query

filter = msiempy.query.FieldFilter(name='DstIP',values=['10.1.13.0/24'],operator='IN')
customfilter = filter.config_dict

events = msiempy.event.EventManager(
        time_range='LAST_MINUTE',
        filters=[
        msiempy.query.FieldFilter('DstIP', ['8.8.0.0/8',]),
        msiempy.query.FieldFilter('HostID', ['mydomain.local'], operator='CONTAINS') ],
        limit=1,
        max_query_depth=1)
events.load_data(delta='2h', slots='4', workers=5)
print(events.get_text(fields=['Alert.SrcPort', 'Rule.NormID']))
```

##### Output
```
INFO - New ESM session instance is created with : [REDACTED]
Traceback (most recent call last):
  File "event.py", line 13, in <module>
    max_query_depth=1)
  File "/usr/local/lib/python3.6/dist-packages/msiempy/event.py", line 141, in __init__
    super(self.__class__, self.__class__).filters.__set__(self, filters)
  File "/usr/local/lib/python3.6/dist-packages/msiempy/__init__.py", line 1460, in filters
    self.add_filter(f)
  File "/usr/local/lib/python3.6/dist-packages/msiempy/event.py", line 195, in add_filter
    raise NitroError("Sorry the filters must be either a tuple(fiels, [values]) or a QueryFilter sub class.")
msiempy.NitroError: Sorry the filters must be either a tuple(fiels, [values]) or a QueryFilter sub class.
```

Removing the `filters` keys seems to work, however.

**Comment by tristanlatr** [comment]
Shit I re-structured the classes and now `FieldFilter` and `GroupFilter` classes are in the `event` sub-module. The `query` sub module simply doesn't exists anymore. So it should work as follow 
```python
import msiempy.event

filter = msiempy.event.FieldFilter(name='DstIP',values=['10.1.13.0/24'],operator='IN')

events = msiempy.event.EventManager(
        time_range='LAST_MINUTE',
        filters=[filter],
        limit=1,
        max_query_depth=1)
events.load_data(delta='2h', slots='4', workers=5)
print(events.get_text(fields=['Alert.SrcPort', 'Rule.NormID']))
```
Be sure to have installed the latest version with `pip install --upgrade msiempy`
I'll change the example right now !

**Comment by de0xy** [comment]
Thanks. Looks like it works now!

Also one more minor thing in the `README.md`: 

```py
events.load_data(delta='2h', slots='4', workers=5)
```

Should actually be

```py
events.load_data(delta='2h', slots=4, workers=5)
                                                        ^
```
