### ISSUE TITLE
Rare "Invalid username or password for the ESM" errors

### ISSUE THREAD

**Issue by tristanlatr** [mfesiem/msiempy#67]
**Describe**
Random "Invalid username or password for the ESM" errors.

**SIEM and msiempy versions:**
msiempy verison: 0.2.2
ESM version: 11.2.1

**Additional context**
```
Traceback (most recent call last):
  File "/home/script-server/isrm-scripts/McAfeeSIEM/Alarms/ack_irrelevants.py", line 59, in <module>
    alarms.load_data(pages=args.pages, use_query=True, extra_fields= ['Description', 'Device_URL', 'Alert.DstIP', 'Rule.msg'])
  File "/usr/local/lib/python3.6/site-packages/msiempy/alarm.py", line 182, in load_data
    items, completed = self.qry_load_data(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/msiempy/alarm.py", line 242, in qry_load_data
    page_number=page_number
  File "/usr/local/lib/python3.6/site-packages/msiempy/__init__.py", line 919, in request
    self.login()
  File "/usr/local/lib/python3.6/site-packages/msiempy/__init__.py", line 650, in login
    raise NitroError('Invalid username or password for the ESM')
msiempy.NitroError: Invalid username or password for the ESM
```

**Comment by tristanlatr** [comment]
Happens sometime , but pretty rare

**Comment by tristanlatr** [comment]
Should be fixed in last release

**Comment by tristanlatr** [comment]
Closing this issue as it seems not be a problem anymore since the login() method can be retried
